cve_definition = """
A CVE (Common Vulnerabilities and Exposures) description provides a concise summary of a specific cybersecurity vulnerability, detailing its characteristics, 
potential impact, and affected systems to facilitate vulnerability management.
"""
a_theatre_definition = """
Attack theaters describe the contexts or environments from which cyberattacks can be launched. 
They include Remote attacks originating outside the target network, Limited Remote attacks using short-range technologies (e.g., Bluetooth, Wi-Fi), 
Local attacks requiring logical access to the system, and Physical attacks needing direct physical access to the target.
"""
a_theatre_desc = """
Attack Theaters:
1. Remote
•	Definition: Cyberattacks originating from locations outside the target network.
•	Examples:
o	Public websites
o	DNS services
o	Web browsers
•	Common Methods:
o	Exploiting exposed web servers or APIs
o	Phishing attacks via email or other online communications
________________________________________
2. Limited Remote
•	Definition: Exploits executed from closer proximity using specific technologies with range constraints.
•	Subcategories:
o	Cellular: Attacks launched via cellular networks.
o	Wireless: Exploits initiated through wireless (802.11x) networks.
o	Bluetooth: Attacks targeting devices over Bluetooth communication.
o	Infrared: Exploits using Infrared technology.
o	Line-Of-Sight: Attacks requiring direct visual alignment, such as optical systems.
•	Common Methods:
o	Eavesdropping on Wi-Fi traffic
o	Intercepting Bluetooth connections
o	Exploiting weak infrared signals
________________________________________
3. Local
•	Definition: The attacker has logical local access to a target computer or system to execute the exploit.
•	Access Points:
o	Console login
o	Remote Desktop Protocol (RDP)
o	Secure Shell (SSH)
o	Telnet
•	Common Methods:
o	Exploiting credentials for local access
o	Deploying malware through local sessions
________________________________________
4. Physical
•	Definition: The attacker must have physical access to the target system to carry out the exploit.
•	Examples:
o	Tampering with hardware components
o	Plugging in malicious USB devices
o	Accessing an unattended computer
•	Common Methods:
o	Installing keyloggers or other hardware-based monitoring tools
o	Extracting data directly from storage devices

"""

example_attack_theater_with_labels = """
webs in Ruckus Wireless Unleashed through 200.7.10.102.92 allows a remote attacker to cause a denial of service (Segmentation fault) to the webserver via an unauthenticated crafted HTTP request. This affects C110 E510 H320 H510 M510 R320 R310 R500 R510 R600 R610 R710 R720 R750 T300 T301n T301s T310c T310d T310n T310s T610 T710 and T710s devices.	Remote
A remote code execution vulnerability exists in the way that Microsoft Windows Codecs Library handles objects in memory aka Microsoft Windows Codecs Library Remote Code Execution Vulnerability. This CVE ID is unique from CVE-2020-1425.	Remote
An authentication bypass vulnerability exists in Microsoft YourPhoneCompanion application for Android  in the way the application processes notifications generated by work profiles.This could allow an unauthenticated attacker to view notifications  aka Microsoft YourPhone Application for Android Authentication Bypass Vulnerability.	Physical
On Juniper Networks SRX Series with ICAP (Internet Content Adaptation Protocol) redirect service enabled a double free vulnerability can lead to a Denial of Service (DoS) or Remote Code Execution (RCE) due to processing of a specific HTTP message. Continued processing of this specific HTTP message may result in an extended Denial of Service (DoS). The offending HTTP message that causes this issue may originate both from the HTTP server or the client. This issue affects Juniper Networks Junos OS on SRX Series: 18.1 versions prior to 18.1R3-S9; 18.2 versions prior to 18.2R3-S3; 18.3 versions prior to 18.3R2-S4 18.3R3-S1; 18.4 versions prior to 18.4R2-S5 18.4R3; 19.1 versions prior to 19.1R2; 19.2 versions prior to 19.2R1-S2 19.2R2; 19.3 versions prior to 19.3R2. This issue does not affect Juniper Networks Junos OS prior to 18.1R1.	Remote
On Juniper Networks SRX Series with ICAP (Internet Content Adaptation Protocol) redirect service enabled processing a malformed HTTP message can lead to a Denial of Service (DoS) or Remote Code Execution (RCE) Continued processing of this malformed HTTP message may result in an extended Denial of Service (DoS) condition. The offending HTTP message that causes this issue may originate both from the HTTP server or the HTTP client. This issue affects Juniper Networks Junos OS on SRX Series: 18.1 versions prior to 18.1R3-S9 ; 18.2 versions prior to 18.2R2-S7 18.2R3-S3; 18.3 versions prior to 18.3R1-S7 18.3R2-S4 18.3R3-S1; 18.4 versions prior to 18.4R1-S7 18.4R2-S4 18.4R3; 19.1 versions prior to 19.1R1-S5 19.1R2; 19.2 versions prior to 19.2R1-S2 19.2R2; 19.3 versions prior to 19.3R2. This issue does not affect Juniper Networks Junos OS prior to 18.1R1.	Remote
CarbonFTP v1.4 uses insecure proprietary password encryption with a hard-coded weak encryption key. The key for local FTP server passwords is hard-coded in the binary.	Local
PLCopen XML file parsing in Phoenix Contact PC Worx and PC Worx Express version 1.87 and earlier can lead to a stack-based overflow. Manipulated PC Worx projects could lead to a remote code execution due to insufficient input data validation.	Local
Apache CXF has the ability to integrate with JMX by registering an InstrumentationManager extension with the CXF bus. If the &8216;createMBServerConnectorFactory&8217; property of the default InstrumentationManagerImpl is not disabled  then it is vulnerable to a man-in-the-middle (MITM) style attack. An attacker on the same host can connect to the registry and rebind the entry to another server  thus acting as a proxy to the original. They are then able to gain access to all of the information that is sent and received over JMX.	Limited Rmt
A vulnerability in the multicast DNS (mDNS) protocol configuration of Cisco Webex Meetings Client for MacOS could allow an unauthenticated adjacent attacker to obtain sensitive information about the device on which the Webex client is running. The vulnerability exists because sensitive information is included in the mDNS reply. An attacker could exploit this vulnerability by doing an mDNS query for a particular service against an affected device. A successful exploit could allow the attacker to gain access to sensitive information.	Limited Rmt
Standalone clients connecting to SAP NetWeaver AS Java via P4 Protocol  versions (SAP-JEECOR 7.00  7.01; SERVERCOR 7.10  7.11  7.20  7.30  7.31  7.40  7.50; CORE-TOOLS 7.00  7.01  7.02  7.05  7.10  7.11  7.20  7.30  7.31  7.40  7.50) do not perform any authentication checks for operations that require user identity leading to Authentication Bypass.	Limited Rmt
A vulnerability in the web-based user interface (web UI) of Cisco IOS XE Software could allow an unauthenticated adjacent attacker to bypass access control restrictions on an affected device. The vulnerability is due to the presence of a proxy service at a specific endpoint of the web UI. An attacker could exploit this vulnerability by connecting to the proxy service. An exploit could allow the attacker to bypass access restrictions on the network by proxying their access request through the management network of the affected device. As the proxy is reached over the management virtual routing and forwarding (VRF) this could reduce the effectiveness of the bypass.	Limited Rmt
Certain NETGEAR devices are affected by authentication bypass. This affects D6200 before 1.1.00.30  D7000 before 1.0.1.66  R6020 before 1.0.0.34  R6080 before 1.0.0.34  R6120 before 1.0.0.44  R6220 before 1.1.0.68  WNR2020 before 1.1.0.54  and WNR614 before 1.1.0.54.	Limited Rmt
NETGEAR R9000 devices before 1.0.4.26 are affected by authentication bypass.	Limited Rmt
A vulnerability in Cisco Aironet Series Access Points Software could allow an unauthenticated adjacent attacker to cause a denial of service (DoS) condition on an affected device. The vulnerability is due to the improper processing of client packets that are sent to an affected access point (AP). An attacker could exploit this vulnerability by sending a large number of sustained client packets to the affected AP. A successful exploit could allow the attacker to cause the affected AP to crash resulting in a DoS condition.	Limited Rmt
A vulnerability in the EGG archive parsing module in Clam AntiVirus (ClamAV) Software versions 0.102.0 - 0.102.3 could allow an unauthenticated remote attacker to cause a denial of service condition on an affected device. The vulnerability is due to a null pointer dereference. An attacker could exploit this vulnerability by sending a crafted EGG file to an affected device. An exploit could allow the attacker to cause the ClamAV scanning process crash resulting in a denial of service condition.	Remote
A lock screen issue allowed access to contacts on a locked device. This issue was addressed with improved state management. This issue is fixed in iOS 13.3.1 and iPadOS 13.3.1. A person with physical access to an iOS device may be able to access contacts from the lock screen.	Physical
An inconsistent user interface issue was addressed with improved state management. This issue is fixed in iOS 13.3.1 and iPadOS 13.3.1. A person with physical access to an iOS device may be able to access contacts from the lock screen.	Physical
A logic issue was addressed with improved state management. This issue is fixed in iOS 13.4 and iPadOS 13.4 watchOS 6.2. A person with physical access to a locked iOS device may be able to respond to messages even when replies are disabled.	Physical
NETGEAR RAX40 devices before 1.0.3.64 are affected by authentication bypass.	Limited Rmt

"""


one_shot_attack_theater_example = """
Remote:
    A logic issue was addressed with improved restrictions. This issue is fixed in iOS 13.5 and iPadOS 13.5 tvOS 13.4.5 watchOS 6.2.5 Safari 13.1.1 iTunes 12.10.7 for Windows iCloud for Windows 11.2 iCloud for Windows 7.19. A remote attacker may be able to cause arbitrary code execution. 
Limited Rmt
    An issue was discovered in Zoho ManageEngine AssetExplorer 6.5. During an upgrade of the Windows agent  it does not validate the source and binary downloaded. This allows an attacker on an adjacent network to execute code with NT AUTHORITY/SYSTEM privileges on the agent machines by providing an arbitrary executable via a man-in-the-middle attack.
Local
    Adobe Bridge versions 10.0.1 and earlier version have an use after free vulnerability. Successful exploitation could lead to arbitrary code execution .	
Physical
    Improper Access Control in subsystem for Intel(R) TXE versions before 3.175 and 4.0.25 may allow an unauthenticated user to potentially enable escalation of privilege via physical access.	
"""
five_shot_attack_theater_example = """
Remote examples:
    1. Insufficient data validation in WebUI in Google Chrome prior to 84.0.4147.89 allowed a remote attacker who had compromised the renderer process to inject scripts or HTML into a privileged page via a crafted HTML page.
    2. Incorrect security UI in PWAs in Google Chrome prior to 84.0.4147.89 allowed a remote attacker who had persuaded the user to install a PWA to spoof the contents of the Omnibox (URL bar) via a crafted PWA.
    3. Active IQ Unified Manager for Linux versions prior to 9.6 ship with the Java Management Extension Remote Method Invocation (JMX RMI) service enabled allowing unauthorized code execution to local users.
    4. Adobe Flash Player Desktop Runtime 32.0.0.371 and earlier Adobe Flash Player for Google Chrome 32.0.0.371 and earlier and Adobe Flash Player for Microsoft Edge and Internet Explorer 32.0.0.330 and earlier have an use after free vulnerability. Successful exploitation could lead to arbitrary code execution.
    5. A logic issue was addressed with improved restrictions. This issue is fixed in iOS 13.5 and iPadOS 13.5 tvOS 13.4.5 watchOS 6.2.5 Safari 13.1.1 iTunes 12.10.7 for Windows iCloud for Windows 11.2 iCloud for Windows 7.19. A remote attacker may be able to cause arbitrary code execution. 
Limited Rmt examples:
    An issue was discovered in Zoho ManageEngine AssetExplorer 6.5. During an upgrade of the Windows agent  it does not validate the source and binary downloaded. This allows an attacker on an adjacent network to execute code with NT AUTHORITY/SYSTEM privileges on the agent machines by providing an arbitrary executable via a man-in-the-middle attack.
    A vulnerability in the 802.11r Fast Transition (FT) implementation for Cisco IOS Access Points (APs) Software could allow an unauthenticated adjacent attacker to cause a denial of service (DoS) condition on an affected interface. The vulnerability is due to a lack of complete error handling condition for client authentication requests sent to a targeted interface configured for FT. An attacker could exploit this vulnerability by sending crafted authentication request traffic to the targeted interface causing the device to restart unexpectedly.
    Certain NETGEAR devices are affected by authentication bypass. This affects EX3700 before 1.0.0.64  EX3800 before 1.0.0.64  EX6120 before 1.0.0.32  EX6130 before 1.0.0.16  R6300v2 before 1.0.4.12  R6700 before 1.0.1.26  R6900 before 1.0.1.22  R7000 before 1.0.9.6  R7300DST before 1.0.0.52  R7900 before 1.0.1.12  R8000 before 1.0.3.24  R8500 before 1.0.2.74  and WNR2000v2 before 1.2.0.8.
    RSA BSAFE Micro Edition Suite versions prior to 4.4 (in 4.0.x 4.1.x 4.2.x and 4.3.x) are vulnerable to a Heap-based Buffer Overflow vulnerability when parsing ECDSA signature. A malicious user with adjacent network access could potentially exploit this vulnerability to cause a crash in the library of the affected system.
    There is a man-in-the-middle (MITM) vulnerability on Huawei P30 smartphones versions before ELE-AL00 9.1.0.162(C01E160R1P12/C01E160R2P1)  and P30 Pro versions before VOG-AL00 9.1.0.162 (C01E160R1P12/C01E160R2P1). When users establish connection and transfer data through Huawei Share  an attacker could sniff  spoof and do a series of operations to intrude the Huawei Share connection and launch a man-in-the-middle attack to obtain and tamper the data. (Vulnerability ID: HWPSIRT-2019-03109)

Local examples:
    Adobe Illustrator versions 24.1.2 and earlier have a memory corruption vulnerability. Successful exploitation could lead to arbitrary code execution .
    Adobe Acrobat and Reader versions 2020.006.20042 and earlier  2017.011.30166 and earlier  2017.011.30166 and earlier  and 2015.006.30518 and earlier have a heap overflow vulnerability. Successful exploitation could lead to arbitrary code execution .
    IBM Security Guardium 10.6  11.0  and 11.1 contains hard-coded credentials  such as a password or cryptographic key  which it uses for its own inbound authentication  outbound communication to external components  or encryption of internal data. IBM X-Force ID: 174851.
    mwe file parsing in Phoenix Contact PC Worx and PC Worx Express version 1.87 and earlier is vulnerable to out-of-bounds read remote code execution. Manipulated PC Worx projects could lead to a remote code execution due to insufficient input data validation.
    Kata Containers doesnt restrict containers from accessing the guests root filesystem device. Malicious containers can exploit this to gain code execution on the guest and masquerade as the kata-agent. This issue affects Kata Containers 1.11 versions earlier than 1.11.1; Kata Containers 1.10 versions earlier than 1.10.5; and Kata Containers 1.9 and earlier versions.

Physical examples:
    1. Improper Access Control in subsystem for Intel(R) TXE versions before 3.175 and 4.0.25 may allow an unauthenticated user to potentially enable escalation of privilege via physical access.	
    2. In FreeBSD 12.1-STABLE before r361918 12.1-RELEASE before p6 11.4-STABLE before r361919 11.3-RELEASE before p10 and 11.4-RC2 before p1 an invalid memory location may be used for HID items if the push/pop level is not restored within the processing of that HID item allowing an attacker with physical access to a USB port to be able to use a specially crafted USB device to gain kernel or user-space code execution.
    3. A potential vulnerability in the BIOS configuration of some ThinkSystem models due to missing DMA protections that may allow a user with physical access read or write access to system memory.
    4. Insufficient control flow management in firmware build and signing tool for Intel(R) Innovation Engine before version 1.0.859 may allow an unauthenticated user to potentially enable escalation of privilege via physical access.
    5. An authorization issue was addressed with improved state management. This issue is fixed in iOS 13.5 and iPadOS 13.5. A person with physical access to an iOS device may be able to view notification contents from the lockscreen.

"""
ten_shot_attack_theater_example = """
Remote examples:
    1. Insufficient data validation in WebUI in Google Chrome prior to 84.0.4147.89 allowed a remote attacker who had compromised the renderer process to inject scripts or HTML into a privileged page via a crafted HTML page.
    2. Incorrect security UI in PWAs in Google Chrome prior to 84.0.4147.89 allowed a remote attacker who had persuaded the user to install a PWA to spoof the contents of the Omnibox (URL bar) via a crafted PWA.
    3. Active IQ Unified Manager for Linux versions prior to 9.6 ship with the Java Management Extension Remote Method Invocation (JMX RMI) service enabled allowing unauthorized code execution to local users.
    4. Adobe Flash Player Desktop Runtime 32.0.0.371 and earlier Adobe Flash Player for Google Chrome 32.0.0.371 and earlier and Adobe Flash Player for Microsoft Edge and Internet Explorer 32.0.0.330 and earlier have an use after free vulnerability. Successful exploitation could lead to arbitrary code execution.
    5. A logic issue was addressed with improved restrictions. This issue is fixed in iOS 13.5 and iPadOS 13.5 tvOS 13.4.5 watchOS 6.2.5 Safari 13.1.1 iTunes 12.10.7 for Windows iCloud for Windows 11.2 iCloud for Windows 7.19. A remote attacker may be able to cause arbitrary code execution. 
    6. Insufficient policy enforcement in V8 in Google Chrome prior to 14.0.0.0 allowed a remote attacker to obtain potentially sensitive information from process memory via a crafted HTML page.
    7. Insufficient policy enforcement in WebView in Google Chrome on Android prior to 83.0.4103.106 allowed a remote attacker to bypass site isolation via a crafted HTML page.
    8. Out of bounds write in Skia in Google Chrome prior to 84.0.4147.89 allowed a remote attacker to potentially exploit heap corruption via a crafted HTML page.
    9. Out of bounds write in V8 in Google Chrome prior to 81.0.4044.92 allowed a remote attacker to potentially exploit heap corruption via a crafted HTML page.
    10. Use after free in media in Google Chrome prior to 83.0.4103.61 allowed a remote attacker who had compromised the renderer process to potentially perform a sandbox escape via a crafted HTML page.


Limited Rmt examples:
    1. An issue was discovered in Zoho ManageEngine AssetExplorer 6.5. During an upgrade of the Windows agent  it does not validate the source and binary downloaded. This allows an attacker on an adjacent network to execute code with NT AUTHORITY/SYSTEM privileges on the agent machines by providing an arbitrary executable via a man-in-the-middle attack.
    2. A vulnerability in the 802.11r Fast Transition (FT) implementation for Cisco IOS Access Points (APs) Software could allow an unauthenticated adjacent attacker to cause a denial of service (DoS) condition on an affected interface. The vulnerability is due to a lack of complete error handling condition for client authentication requests sent to a targeted interface configured for FT. An attacker could exploit this vulnerability by sending crafted authentication request traffic to the targeted interface causing the device to restart unexpectedly.
    3. Certain NETGEAR devices are affected by authentication bypass. This affects EX3700 before 1.0.0.64  EX3800 before 1.0.0.64  EX6120 before 1.0.0.32  EX6130 before 1.0.0.16  R6300v2 before 1.0.4.12  R6700 before 1.0.1.26  R6900 before 1.0.1.22  R7000 before 1.0.9.6  R7300DST before 1.0.0.52  R7900 before 1.0.1.12  R8000 before 1.0.3.24  R8500 before 1.0.2.74  and WNR2000v2 before 1.2.0.8.
    4. RSA BSAFE Micro Edition Suite versions prior to 4.4 (in 4.0.x 4.1.x 4.2.x and 4.3.x) are vulnerable to a Heap-based Buffer Overflow vulnerability when parsing ECDSA signature. A malicious user with adjacent network access could potentially exploit this vulnerability to cause a crash in the library of the affected system.
    5. There is a man-in-the-middle (MITM) vulnerability on Huawei P30 smartphones versions before ELE-AL00 9.1.0.162(C01E160R1P12/C01E160R2P1)  and P30 Pro versions before VOG-AL00 9.1.0.162 (C01E160R1P12/C01E160R2P1). When users establish connection and transfer data through Huawei Share  an attacker could sniff  spoof and do a series of operations to intrude the Huawei Share connection and launch a man-in-the-middle attack to obtain and tamper the data. (Vulnerability ID: HWPSIRT-2019-03109)
    6. Improper conditions check for Intel(R) Modular Server MFS2600KISPP Compute Module may allow an unauthenticated user to potentially enable escalation of privilege via adjacent access.
    7. Certain NETGEAR devices are affected by authentication bypass. This affects D6200 before 1.1.00.34  D7000 before 1.0.1.68  JR6150 before 1.0.1.18  PR2000 before 1.0.0.28  R6050 before 1.0.1.18  R6120 before 1.0.0.46  R6220 before 1.1.0.80  R6260 before 1.1.0.64  R6700v2 before 1.2.0.36  R6800 before 1.2.0.36  and R6900v2 before 1.2.0.36.
    8. Legacy pairing and secure-connections pairing authentication in Bluetooth  BR/EDR Core Specification v5.2 and earlier may allow an unauthenticated user to complete authentication without pairing credentials via adjacent access. An unauthenticated adjacent attacker could impersonate a Bluetooth BR/EDR master or slave to pair with a previously paired remote device to successfully complete the authentication procedure without knowing the link key.
    9. This vulnerability allows network-adjacent attackers to bypass authentication on affected installations of D-Link DIR-867  DIR-878  and DIR-882 routers with firmware 1.10B04. Authentication is not required to exploit this vulnerability. The specific flaw exists within the handling of HNAP login requests. The issue results from the lack of proper implementation of the authentication algorithm. An attacker can leverage this vulnerability to escalate privileges and execute code in the context of the router. Was ZDI-CAN-9470.
    10 The Help feature in the ES File Explorer File Manager application 4.1.9.7.4 for Android allows session hijacking by a Man-in-the-middle attacker on the local network because HTTPS is not used  and an attackers web site is displayed in a WebView with no information about the URL.


Local examples:
    1. Adobe Illustrator versions 24.1.2 and earlier have a memory corruption vulnerability. Successful exploitation could lead to arbitrary code execution .
    2. Adobe Acrobat and Reader versions 2020.006.20042 and earlier  2017.011.30166 and earlier  2017.011.30166 and earlier  and 2015.006.30518 and earlier have a heap overflow vulnerability. Successful exploitation could lead to arbitrary code execution .
    3. IBM Security Guardium 10.6  11.0  and 11.1 contains hard-coded credentials  such as a password or cryptographic key  which it uses for its own inbound authentication  outbound communication to external components  or encryption of internal data. IBM X-Force ID: 174851.
    4. mwe file parsing in Phoenix Contact PC Worx and PC Worx Express version 1.87 and earlier is vulnerable to out-of-bounds read remote code execution. Manipulated PC Worx projects could lead to a remote code execution due to insufficient input data validation.
    5. Kata Containers doesnt restrict containers from accessing the guests root filesystem device. Malicious containers can exploit this to gain code execution on the guest and masquerade as the kata-agent. This issue affects Kata Containers 1.11 versions earlier than 1.11.1; Kata Containers 1.10 versions earlier than 1.10.5; and Kata Containers 1.9 and earlier versions.
    6. Use of a hard-coded cryptographic key to encrypt security sensitive data in local storage and configuration in FortiClient for Windows prior to 6.4.0 may allow an attacker with access to the local storage or the configuration backup file to decrypt the sensitive data via knowledge of the hard-coded key.
    7. A CWE-89: Improper Neutralization of Special Elements used in an SQL Command (SQL Injection) vulnerability exists in EcoStruxure Operator Terminal Expert 3.1 Service Pack 1 and prior (formerly known as Vijeo XD) which could cause malicious code execution when opening the project file.
    8. Adobe Bridge versions 10.0.1 and earlier version have an out-of-bounds write vulnerability. Successful exploitation could lead to arbitrary code execution .
    9. NVIDIA Windows GPU Display Driver  all versions  contains a vulnerability in the service host component  in which the application resources integrity check may be missed. Such an attack may lead to code execution  denial of service or information disclosure.
    10. Adobe Acrobat and Reader versions 2020.006.20042 and earlier  2017.011.30166 and earlier  2017.011.30166 and earlier  and 2015.006.30518 and earlier have an use-after-free vulnerability. Successful exploitation could lead to arbitrary code execution .


Physical examples:
    1. Improper Access Control in subsystem for Intel(R) TXE versions before 3.175 and 4.0.25 may allow an unauthenticated user to potentially enable escalation of privilege via physical access.	
    2. In FreeBSD 12.1-STABLE before r361918 12.1-RELEASE before p6 11.4-STABLE before r361919 11.3-RELEASE before p10 and 11.4-RC2 before p1 an invalid memory location may be used for HID items if the push/pop level is not restored within the processing of that HID item allowing an attacker with physical access to a USB port to be able to use a specially crafted USB device to gain kernel or user-space code execution.
    3. A potential vulnerability in the BIOS configuration of some ThinkSystem models due to missing DMA protections that may allow a user with physical access read or write access to system memory.
    4. Insufficient control flow management in firmware build and signing tool for Intel(R) Innovation Engine before version 1.0.859 may allow an unauthenticated user to potentially enable escalation of privilege via physical access.
    5. An authorization issue was addressed with improved state management. This issue is fixed in iOS 13.5 and iPadOS 13.5. A person with physical access to an iOS device may be able to view notification contents from the lockscreen.
    6. Inappropriate implementation in iframe sandbox in Google Chrome prior to 84.0.4147.89 allowed a remote attacker to bypass navigation restrictions via a crafted HTML page.
    7. Insufficient policy enforcement in CSP in Google Chrome prior to 84.0.4147.89 allowed a remote attacker to bypass content security policy via a crafted HTML page.
    8. Incorrect security UI in basic auth in Google Chrome on iOS prior to 84.0.4147.89 allowed a remote attacker to spoof the contents of the Omnibox (URL bar) via a crafted HTML page.
    9. Inappropriate implementation in WebRTC in Google Chrome prior to 84.0.4147.89 allowed an attacker in a privileged network position to leak cross-origin data via a crafted HTML page.
    10. Out of bounds memory access in developer tools in Google Chrome prior to 84.0.4147.89 allowed an attacker who convinced a user to install a malicious extension to potentially exploit heap corruption via a crafted Chrome Extension.

"""

#Good prompt in case you lose it or it changes;
# prompt = (
#         f"You are an expert in classifying CVE (Common Vulnerabilities and Exposures) based on detailed descriptions. "
#         f"Below are some definitions and descriptions to guide you:\n\n"
#         f"CVE Definition: {cve_definition}\n"
#         f"Attack Theatre Description: {a_theatre_desc}\n"
#         f"Attack Theatre Definition: {a_theatre_definition}\n\n"
#         f"Here is the CVE description for you to classify: {cve_description}\n"
#         # f"Your task is to label the CVE description with one or more labels from the Attack Theatre VDO noun group. "
#         f"Your task is to label the CVE description with the most relevant Attack Theatre Vector label. "
#         f"Evaluate each Attack Theatre Vector label to determine if the CVE description falls under that category (e.g., Remote, Limited Rmt, Local, Physical). "
#         f"Here is a list of examples of CVE descriptions and their corresponding labels: ```{example_cve_with_labels}```\n"
#         # f"Your final output should be a comma-separated list of all applicable VDO labels, or a single label if only one applies. "
#         f"Your final output should be the label that best characterizes the CVE description. (e.g. Remote, Limited Rmt, Local, Physical)"
#         f"Your final output should be one of the following: 'Remote', 'Limited Rmt', 'Local', 'Physical'\n"
#         f"Remember, return ONLY the label name. Do not explain your reasoning or provide any other output. Don't even add a period after the label."
#         # f"Ask yourself the following questions to help you come up with your final response: {questions_to_be_answered}"
#         # f"Remember, return ONLY the label name(s) as a comma-separated list if more than one applies. Do not explain your reasoning or provide any other output."
#     )

